[package]
name = "structure"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.*"
pathdiff = "0.2.2"
serde = {version = "1.0.*", features = ["derive"]}
serde_json = "1.0.*"
log = "0.4.*"
logforth = {  version = "0.13.0", features = ["rolling_file"] }
regex = "1.11.0"